---
title: "Curriculum Vitae"
description: |
  Latin for "course of life"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center>

# JOSHUA O. S. HUNT, CPA

</center>

------------------------------------------------------------------------

## ACADEMIC EMPLOYMENT

### Louisiana Tech University, Ruston, LA

Adjunct Instructor: September 2022 - Present.

### Mississippi State University, Starkville, MS

Assistant Professor: August 2018 -- August 2022.

### University of Arkansas, Fayetteville, AR

Research Assistant and Instructor: 2013-2018.

Graduate Assistant: 2012-2013.

## EDUCATION

### University of Arkansas, Fayetteville, AR

PhD in Business Administration - Accounting Emphasis -- Completed Summer 2018

Master of Statistics and Business Analytics -- Completed 2017

Master of Accountancy -- Completed 2013

### Louisiana Tech University, Ruston, LA

Master of Arts in Teaching - Mathematics Emphasis -- Completed 2011

Bachelor of Science -- Mathematics Major, Finance Minor -- Completed 2008

## RESEARCH

### Interests

#### Business Analytics

-   Machine learning algorithms

-   Outlier analysis

-   Clustering

-   Measuring model fit

#### Accounting

-   Earnings/Returns Relation

-   Methodology

### Dissertation

"A Data Analytics Approach to Classification in an Accounting Setting: Predicting Changes in Earnings"

Committee: Vernon Richardson (Chair), Cory Cassell, David Douglas, and James Myers

### Publications

Hunt, J. O., Rosser, D. M., & Rowe, S. P. (2020). Using machine learning to predict auditor switches: How the likelihood of switching affects audit quality among non-switching clients. Journal of Accounting and Public Policy, 106785.

Hunt, J., Myers, J., & Myers, L. (2021). Improving earnings predictions with machine learning. Forthcoming Accounting Horizons.

Hunt, E., Hunt, J., Richardson, V., & David, R. (2021). Auditor Response to Estimated Misstatement Risk: A Machine Learning Approach. Forthcoming Accounting Horizons.

### Circulated Work

Cunningham, L., Hunt, J., and Short, J. Appointing audit committee directors.

Dearden, S., Hunt, E., Hunt, J., and Richardson, V. Combining expert expectations with machine learning: An analysis of bank going concern opinions before and after the financial crisis.

Hunt, E., Hunt, J., and Rosser, D. The effect of lockdowns during the pandemic on audit outcomes.

### Works in Progress

Hunt, E., Hunt, J., and Kang, Dae. A Simple Way to Measure Binary Model Fit.

-   New technique derived and tested on real data

## CONFERENCES ATTENDED

AAA FARS Section Midyear -- 2014, 2015, 2017

Arkansas Accounting Research Conference -- 2014, 2015, 2016, 2017, 2018

OSU Accounting Research Conference -- 2015, 2018

AAA Audit Section Midyear -- 2017, 2018, 2019

AAA AIS Section Midyear - 2019

AAA Southwest Regional Meeting -- 2017

AAA Accounting Information Systems Section Bootcamp - 2017

## TEACHING INTERESTS

Business Analytics

Accounting Information Systems

Cost/Management Accounting

Financial Accounting

## TEACHING EXPERIENCE

### Mississippi State University

Accounting Data Analytics - 2021

Accounting Information Systems II -2021, 2022

Accounting Information Systems I -- 2018, 2019, 2020

Principles of Financial Accounting -- 2019

### University of Arkansas, Fayetteville, AR

Intermediate Accounting II -- 2014, 2015

Accounting Principles I -- 2015

Cost Accounting -- 2016, 2018

## PROFESSIONAL CERTIFICATIONS

Certified Public Accountant, Arkansas

## SERVICE

### Ad Hoc Reviewer

International Journal of Accounting Information Systems -- 2018, 2019, 2020, 2021, 2022

Journal of Information systems - 2020

Accounting Horizons -- 2018, 2019, 2022

Review of Accounting Studies - 2021

Finance Research Letters - 2022

### Committees

Accounting Horizons Data Analytics Conference 2019 Scientific Committee Member

Richard C. Adkerson School of Accountancy Curriculum Committee and Strategic Planning Committee

MSU College of Business Scholarship Committee

### Editorial Board

International Journal of Accounting Information Systems Editorial Board Member - 2022

## Honors

Mississippi State University College of Business undergraduate critical thinking project design 2019

Accounting Information Systems (including topics about technology in accounting)" track for the Best Reviewer's Award HARC 2022

## PROGRAMMING EXPERIENCE

R, SAS, SAS Enterprise Miner, SPSS Miner, Microsoft SQL server, Stata, Python
